name: lurc
description: "A native Android API client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
